spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydemy?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      authentication-database: admin
      username: mydemy
      password: mydemy
      database: mydemy
      port: 27017
      host: localhost
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  

###############################################
########### MYDEMY PROPERTIES ###############
###############################################
