package it.univaq.disim.mwt.mydemy.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

import it.univaq.disim.mwt.mydemy.domain.Categoria;

public interface CategoriaRepository extends JpaRepository<Categoria, Long> {
	//Implementation AUTO-GENERATED By Spring-Data-Jpa

	List<Categoria> findByParentIsNull();

	List<Categoria> findCategoriaByParent(Categoria catgeoria);
}
