package it.univaq.disim.mwt.mydemy.repository;

import java.util.List;
import java.util.Optional;

import it.univaq.disim.mwt.mydemy.domain.Categoria;
import it.univaq.disim.mwt.mydemy.domain.Utente;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.univaq.disim.mwt.mydemy.domain.Corso;
@Repository
public interface CorsoRepository extends JpaRepository<Corso, Long> {
	//Implementation AUTO-GENERATED By Spring-Data-Jpa
	
	List<Corso> findByTitoloContainingIgnoreCaseAndApprovatoIsTrue(String titolo, Pageable paging);

    List<Corso> findByTitoloContainingIgnoreCase(String titolo, Pageable paging);

    List<Corso> findByApprovatoIsTrue(Pageable pageable);
    
    List<Corso> findByCreatore(Utente creatore);

    Optional<Corso> findByIdAndCreatore(Long id, Utente creatore);

    List<Corso> findAllByCreatoreOrderByFineDescApprovatoDesc(Utente creatore, Pageable pageable);

    List<Corso> findAllByCreatoreAndTitoloContainingIgnoreCaseOrderByFineDescApprovatoDesc(Utente creatore, String title, Pageable pageable);

    List<Corso> findByTitoloContainingIgnoreCaseOrTagsNomeContainingIgnoreCaseOrCreatoreNomeContainingIgnoreCaseOrCreatoreCognomeContainingIgnoreCaseAndApprovatoIsTrue(String titolo, String tagNome, String creatoreNome, String creatoreCognome, Pageable pageable);

    List<Corso> findByCategorie_AndTitoloContainingIgnoreCaseOrTagsNomeContainingIgnoreCaseOrCreatoreNomeContainingIgnoreCaseOrCreatoreCognomeContainingIgnoreCaseAndApprovatoIsTrue(Categoria categoria, String titolo, String tagNome, String creatoreNome, String creatoreCognome, Pageable pageable);
}
