package it.univaq.disim.mwt.mydemy.repository;

import java.util.List;
import java.util.Optional;

import it.univaq.disim.mwt.mydemy.domain.Categoria;
import it.univaq.disim.mwt.mydemy.domain.Utente;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import it.univaq.disim.mwt.mydemy.domain.Corso;
@Repository
public interface CorsoRepository extends JpaRepository<Corso, Long>, CorsoRepositoryCustom {
	//Implementation AUTO-GENERATED By Spring-Data-Jpa
	
	public List<Corso> findByTitoloContainingIgnoreCaseAndApprovatoIsTrue(String titolo, Pageable paging);
	
    public List<Corso> findByTitoloContainingIgnoreCase(String titolo, Pageable pageable);
    
    public List<Corso> findByCreatore(Utente creatore);

    Optional<Corso> findByIdAndCreatore(Long id, Utente creatore);

    public List<Corso> findAllByCreatoreOrderByFineDescApprovatoDesc(Utente creatore, Pageable pageable);

    public List<Corso> findAllByCreatoreAndTitoloContainingIgnoreCaseOrderByFineDescApprovatoDesc(Utente creatore, String title, Pageable pageable);

    public List<Corso> findByCategorie_AndTitoloContainingIgnoreCaseAndApprovatoIsTrue(Categoria categoria, String searchString, Pageable pageable);
}
