package it.univaq.disim.mwt.mydemy.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

import it.univaq.disim.mwt.mydemy.domain.Tag;

public interface TagRepository extends JpaRepository<Tag, Long> {
	//Implementation AUTO-GENERATED By Spring-Data-Jpa
	public List<Tag> findByNomeIgnoreCaseContaining(String nomeTag);
}
