package it.univaq.disim.mwt.mydemy.repository;


import org.springframework.data.jpa.repository.JpaRepository;

import it.univaq.disim.mwt.mydemy.domain.Corso;
import it.univaq.disim.mwt.mydemy.domain.WebLink;

public interface WebLinkRepository extends JpaRepository<WebLink, Long> {
	//Implementation AUTO-GENERATED By Spring-Data-Jpa
}
